name: .NET CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore CQRSSolution.sln
    - name: Build
      run: dotnet build CQRSSolution.sln --no-restore
    - name: Test
      run: dotnet test CQRSSolution.sln --no-build --verbosity normal
